//
//  SearchWireframe.swift
//  RecipePTest
//
//  Created by Pablo Vélez  on 19/10/18.
//  Copyright (c) 2018 Denis Menendez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SearchWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "SearchViewController", bundle: nil)

    // MARK: - Module setup -

    func configureModule(with viewController: SearchViewController) {
        let interactor = SearchInteractor()
        let presenter = SearchPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
    }

    // MARK: - Transitions -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: SearchViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = SearchInteractor()
        let presenter = SearchPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension SearchWireframe: SearchWireframeInterface {

    func navigate(to option: SearchNavigationOption) {
    }
}
